"use strict";

const canvas = document.getElementById("gameCanvas");
const ctx = canvas.getContext("2d");
const W = canvas.width;
const H = canvas.height;
const LANES = [205, 365, 525];
const query = new URLSearchParams(location.search);
const testMode = query.has("test");
const testScreen = query.get("screen");
const $ = id => document.getElementById(id);
const ui = Object.fromEntries(["hud","heartMeter","durabilityValue","scoreValue","waveValue","levelValue","xpValue","ultimateBadge","startScreen","startButton","loadingJourney","loadingTitle","loadingStatus","loadingProgress","countdown","upgradeScreen","choiceEyebrow","choiceTitle","endScreen","endEyebrow","endTitle","endMessage","finalScore","restartButton","toast","cinematic","memoryScreen","memoryCard","memoryDate","memoryTitle","memoryText","memoryImages","memoryBackTitle","flipMemoryButton","keepMemoryButton","cardHand","giftScreen","giftChestButton","giftMessage","finalRescue","finalChestButton","audioToggle","bgm"].map(id => [id, $(id)]));
const testTools = $("testTools");
const testStatus = $("testStatus");
if (testMode) testTools.classList.remove("hidden");

const paths = {
  background: "game-assets/backgrounds/main.png",
  wave: "game-assets/world/bottom-wave.png",
  tallWave: "game-assets/world/tall-wave.png",
  barrier: "game-assets/world/wave-barrier.png",
  gate: "game-assets/world/dragon-gate.png",
  chest: "game-assets/ui/chest.png",
  heart: Array.from({length:3},(_,i)=>`game-assets/ui/hearts/heart_${String(i+1).padStart(2,"0")}.png`),
  player: Array.from({length:5},(_,i)=>`game-assets/characters/player/swim_${String(i+1).padStart(2,"0")}.png`),
  summon: Array.from({length:4},(_,i)=>`game-assets/characters/summon/front_${String(i+1).padStart(2,"0")}.png`),
  bullet: Array.from({length:3},(_,i)=>`game-assets/effects/bullet/frame_${String(i+1).padStart(2,"0")}.png`),
  bomb: Array.from({length:3},(_,i)=>`game-assets/effects/bomb/frame_${String(i+1).padStart(2,"0")}.png`),
  anxiety: Array.from({length:3},(_,i)=>`game-assets/enemies/anxiety/frame_${String(i+1).padStart(2,"0")}.png`),
  weight: Array.from({length:3},(_,i)=>`game-assets/enemies/weight-gain/frame_${String(i+1).padStart(2,"0")}.png`),
  anger: Array.from({length:3},(_,i)=>`game-assets/enemies/anger/frame_${String(i+1).padStart(2,"0")}.png`),
  octopus: Array.from({length:3},(_,i)=>`game-assets/bosses/octopus/frame_${String(i+1).padStart(2,"0")}.png`),
  shark: Array.from({length:3},(_,i)=>`game-assets/bosses/shark/frame_${String(i+1).padStart(2,"0")}.png`)
};
paths.memories=Array.from({length:6},(_,i)=>`game-assets/memories/${String(i+1).padStart(2,"0")}-${["april-embrace","may-roses","may20-gifts","june-flowers","june-food","july-study"][i]}.jpg`);
paths.finalMemories=Array.from({length:4},(_,i)=>`game-assets/memories/final-sketch-${String(i+1).padStart(2,"0")}.jpg`);
const images = {};
const assetPaths=[...new Set(Object.values(paths).flat())];
let loadedAssets=0;
const totalAssets=assetPaths.length+1;
function updateLoading(label){loadedAssets++;const percent=Math.round(loadedAssets/totalAssets*100);ui.loadingProgress.style.width=`${percent}%`;ui.loadingStatus.textContent=`${label} · ${percent}%`;}
function load(path){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{images[path]=image;updateLoading("回忆正在发光");resolve();};image.onerror=()=>reject(path);image.src=path;});}
async function loadMusic(){const response=await fetch(ui.bgm.getAttribute("src"),{cache:"force-cache"});if(!response.ok)throw new Error("background music");const blob=await response.blob();ui.bgm.src=URL.createObjectURL(blob);ui.bgm.load();updateLoading("旋律已经抵达");}
let ready=false;
ui.startScreen.classList.add("loading");
Promise.all([...assetPaths.map(load),loadMusic()]).then(()=>{ready=true;draw(0);ui.loadingTitle.textContent="回忆已经收好，我们一起出发";ui.loadingStatus.textContent="全部就绪 · 100%";ui.loadingProgress.style.width="100%";setTimeout(()=>{ui.loadingJourney.classList.add("ready");ui.startScreen.classList.remove("loading");ui.startButton.disabled=false;ui.startButton.textContent="开始游";if(testMode&&testScreen==="choice"){reset();setTimeout(()=>openChoices(false),80);}},700);}).catch(error=>{console.error("Asset failed",error);ui.loadingTitle.textContent="有一朵浪花迟到了";ui.loadingStatus.textContent="请刷新页面再试一次";});

const baseStats = () => ({damage:2,fireRate:1,bulletCount:1,penetrate:0,crit:.05,critDamage:2,bulletSpeed:1,explosion:0,explosionRadius:105,explosionDamage:1,maxDurability:100,healOnKill:0,damageReduction:0,shieldInterval:0,slow:0,rageReduction:0,block:.0});
const state = {phase:"menu",lane:1,durability:100,score:0,wave:1,totalWaves:20,waveTime:0,waveLength:testMode?60:10,spawnTime:0,bombTime:0,shotTime:0,level:1,xp:0,xpNeed:5,ultimate:0,invincible:0,shield:0,shieldClock:0,summon:0,worldX:0,shake:0,hurtFlash:0,endingTime:0,nextMemory:0,collected:[],revealed:[],activeMemory:null,memoryResume:"playing",tripleShot:0,powerBuff:0,freezeTime:0,debuffTime:0,finalAssist:0,finalCardDelay:0,finalStoryShown:false,finalVictoryPending:false,stats:baseStats(),bullets:[],enemyShots:[],enemies:[],chests:[],effects:[],eliteSpawned:false,bossSpawned:false,choices:[]};

const memoryCards=[
  {date:"4 \u6708",title:"\u98ce\u91cc\u7684\u62e5\u62b1",text:"\u90a3\u5929\u98ce\u5f88\u5927\uff0c\u6211\u4eec\u5728\u98ce\u91cc\u76f8\u62e5\u3002\u8def\u706f\u628a\u5f71\u5b50\u62c9\u5f97\u5f88\u957f\uff0c\u6211\u60f3\u548c\u5b9d\u5b9d\u4e00\u8d77\u8d70\u5f88\u4e45\u5f88\u4e45\u3002",skill:"\u62e5\u62b1\u62a4\u822a",hint:"\u56de\u6ee1\u5fc3\u7075\u5e76\u83b7\u5f97 2 \u5c42\u62a4\u76fe"},
  {date:"5 \u6708",title:"\u8ba9\u82b1\u671f\u7ee7\u7eed",text:"100 \u5929\u65f6\uff0c\u6211\u4eec\u4e0d\u5fcd\u73ab\u7470\u6162\u6162\u51cb\u8c22\uff0c\u4fbf\u8ba9\u8fd9\u4efd\u7231\u610f\u7ee7\u7eed\u6e29\u67d4\u6d41\u6dcc\u3002",skill:"\u82b1\u671f\u7efd\u653e",hint:"\u5f15\u7206\u5168\u573a\u5e76\u6e05\u9664\u666e\u901a\u602a"},
  {date:"5 \u6708 20 \u65e5",title:"\u76f8\u968f\u4e0e\u5171",text:"\u6211\u4eec\u4ea4\u6362\u4e86\u7b2c\u4e00\u4e2a 520 \u793c\u7269\u3002\u4e0d\u8d1f\u9752\u5c71\uff0c\u76f8\u968f\u4e0e\u5171\uff1b\u6211\u4eec\u4f1a\u7ad9\u5728\u5f7c\u6b64\u7684\u524d\u9014\u91cc\u3002",skill:"\u4e09\u8def\u540c\u884c",hint:"10 \u79d2\u4e09\u8def\u9f50\u5c04\uff0c\u4f24\u5bb3 +50%"},
  {date:"6 \u6708\u521d",title:"\u5411\u9633\u751f\u957f",text:"\u6211\u4eec\u7b2c\u4e00\u6b21\u4e00\u8d77\u63d2\u82b1\u3002\u6211\u4eec\u90fd\u559c\u6b22\u5411\u65e5\u8475\uff0c\u6211\u4eec\u7684\u672a\u6765\u4e5f\u4f1a\u50cf\u5b83\u4e00\u6837\u707f\u70c2\u3002",skill:"\u5411\u9633\u52a0\u901f",hint:"12 \u79d2\u653b\u901f\u3001\u5b50\u5f39\u4f24\u5bb3\u5927\u5e45\u63d0\u5347"},
  {date:"6 \u6708\u4e2d",title:"\u5e78\u798f\u52a0\u9910",text:"\u5e78\u798f\u7684\u79d8\u8bc0\u662f\u5403\u597d\u591a\u597d\u591a\u597d\u5403\u7684\uff0c\u4f46\u771f\u6b63\u7684\u79d8\u8bc0\uff0c\u662f\u6211\u4eec\u4e00\u76f4\u5728\u4e00\u8d77\u3002",skill:"\u5e78\u798f\u8865\u7ed9",hint:"\u56de\u590d\u5fc3\u7075\uff0c6 \u79d2\u65e0\u654c\u4e0e\u51cf\u901f"},
  {date:"7 \u6708\u521d",title:"\u5e76\u80a9\u8d76\u8def",text:"\u6211\u4eec\u6b63\u5728\u7ecf\u5386\u4e00\u573a\u4f1f\u5927\u7684\u8bd5\u70bc\uff0c\u5e78\u597d\u4e00\u8def\u6709\u5f7c\u6b64\u3002\u7b49\u660e\u5e74\uff0c\u7b49\u672a\u6765\uff0c\u6211\u4eec\u4f1a\u8d8a\u6765\u8d8a\u5e78\u798f\u3002",skill:"\u5e76\u80a9\u51b2\u523a",hint:"\u6e05\u5f39\u5e55\uff0c10 \u79d2\u51bb\u7ed3\u654c\u4eba\u5e76\u4e09\u8def\u9f50\u5c04"}
];
const finalMemory={date:"7 \u6708 20 \u65e5",title:"\u6211\u4eec\u4e00\u8d77\u753b\u4e0b\u7684\u672a\u6765",text:"\u96c6\u8bad\u524d\u4e00\u665a\uff0c\u6211\u4eec\u542b\u7740\u773c\u6cea\u8bf4\u51fa\u5fc3\u91cc\u7684\u62c5\u5fe7\u3002\u539f\u6765\u6211\u4eec\u90fd\u5728\u4e3a\u5171\u540c\u7684\u672a\u6765\u594b\u6597\u3002\u90a3\u5929\u7684\u624b\u7a3f\uff0c\u6211\u505a\u6210\u4e86\u8fd9\u6b3e\u6e38\u620f\u3002\u6211\u4eec\u4e00\u5b9a\u80fd\u8d8a\u8fc7\u9f99\u95e8\uff0c\u4e00\u8d77\u4e0a\u5cb8\u3002"};

let audioContext=null,audioMuted=false;
ui.bgm.volume=.32;
function unlockAudio(){if(!audioContext)audioContext=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume();if(!audioMuted)ui.bgm.play().catch(()=>{});}
function sfx(kind){if(audioMuted)return;unlockAudio();const now=audioContext.currentTime,gain=audioContext.createGain(),osc=audioContext.createOscillator();osc.connect(gain).connect(audioContext.destination);const settings={popup:[620,920,.16,"sine"],flip:[360,720,.2,"triangle"],hit:[150,95,.11,"square"],hurt:[130,62,.24,"sawtooth"],explosion:[105,36,.42,"sawtooth"],chest:[440,1040,.5,"sine"],win:[520,1180,.7,"triangle"]}[kind]||[440,660,.12,"sine"];osc.type=settings[3];osc.frequency.setValueAtTime(settings[0],now);osc.frequency.exponentialRampToValueAtTime(settings[1],now+settings[2]);gain.gain.setValueAtTime(kind==="explosion"?.13:.07,now);gain.gain.exponentialRampToValueAtTime(.001,now+settings[2]);osc.start(now);osc.stop(now+settings[2]);if(kind==="explosion"){const buffer=audioContext.createBuffer(1,audioContext.sampleRate*.32,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,2);const noise=audioContext.createBufferSource(),noiseGain=audioContext.createGain();noise.buffer=buffer;noiseGain.gain.setValueAtTime(.12,now);noiseGain.gain.exponentialRampToValueAtTime(.001,now+.32);noise.connect(noiseGain).connect(audioContext.destination);noise.start(now);}}
function toggleAudio(){audioMuted=!audioMuted;ui.bgm.muted=audioMuted;ui.audioToggle.classList.toggle("muted",audioMuted);ui.audioToggle.textContent=audioMuted?"\u266a":"\u266b";ui.audioToggle.title=audioMuted?"\u5f00\u542f\u97f3\u4e50":"\u5173\u95ed\u97f3\u4e50";ui.audioToggle.setAttribute("aria-label",ui.audioToggle.title);if(!audioMuted)unlockAudio();}

const pools = {
  study:[
    {icon:"\u540c",name:"\u9ed8\u5951\u52a0\u500d",desc:"\u6bcf\u6b21\u591a\u53d1\u5c04 1 \u679a\u5b50\u5f39（\u6700\u591a 5 \u679a）",available:s=>s.bulletCount<5,apply:s=>s.bulletCount++},
    {icon:"\u901a",name:"\u4e00\u8def\u8d2f\u901a",desc:"\u5b50\u5f39\u989d\u5916\u7a7f\u900f 1 \u4e2a\u654c\u4eba",apply:s=>s.penetrate++},
    {icon:"\u7834",name:"\u52bf\u5982\u7834\u7af9",desc:"\u5b50\u5f39\u4f24\u5bb3 +25%",apply:s=>s.damage*=1.25},
    {icon:"\u8d8a",name:"\u5954\u5411\u5f7c\u5cb8",desc:"\u5b50\u5f39\u901f\u5ea6 +20%",apply:s=>s.bulletSpeed*=1.2},
    {icon:"\u7075",name:"\u5fc3\u6709\u7075\u7280",desc:"\u66b4\u51fb\u7387 +12%",apply:s=>s.crit=Math.min(.65,s.crit+.12)},
    {icon:"\u70bd",name:"\u70bd\u70ed\u56de\u54cd",desc:"\u66b4\u51fb\u4f24\u5bb3 +40%",apply:s=>s.critDamage+=.4},
    {icon:"\u5e76",name:"\u5e76\u80a9\u8d76\u8def",desc:"\u653b\u901f +18%",apply:s=>s.fireRate*=1.18},
    {icon:"\u54cd",name:"\u7231\u6709\u56de\u54cd",desc:"\u89e3\u9501\u547d\u4e2d\u8303\u56f4\u7206\u70b8",available:s=>!s.explosion,apply:s=>s.explosion=1},
    {icon:"\u6f9c",name:"\u5fc3\u6f6e\u6f8e\u6e43",desc:"\u547d\u4e2d\u7206\u70b8\u8303\u56f4 +35%",available:s=>s.explosion>0,apply:s=>s.explosionRadius=Math.min(235,s.explosionRadius*1.35)},
    {icon:"\u71c3",name:"\u7231\u610f\u71ce\u539f",desc:"\u547d\u4e2d\u7206\u70b8\u4f24\u5bb3 +40%",available:s=>s.explosion>0,apply:s=>s.explosionDamage=Math.min(3.5,s.explosionDamage+.4)}
  ],
  food:[
    {icon:"\u996d",name:"\u5b9d\u5b9d\u8981\u597d\u597d\u5403\u996d",desc:"\u751f\u547d\u4e0a\u9650 +20 \u5e76\u56de\u590d",apply:s=>{s.maxDurability+=20;state.durability=Math.min(s.maxDurability,state.durability+20);}},
    {icon:"\u751c",name:"\u5e78\u798f\u56de\u7518",desc:"\u6bcf\u6b21\u51fb\u6740\u56de\u590d 2 \u70b9，\u53ef\u53e0\u52a0",apply:s=>s.healOnKill+=2},
    {icon:"\u6696",name:"\u6696\u610f\u62a4\u5fc3",desc:"\u6240\u6709\u4f24\u5bb3\u964d\u4f4e 15%",apply:s=>s.damageReduction=Math.min(.6,s.damageReduction+.15)},
    {icon:"\u7231",name:"\u88ab\u7231\u5305\u56f4",desc:"\u6bcf 18 \u79d2\u751f\u6210\u4e00\u5c42\u62a4\u76fe",apply:s=>s.shieldInterval=s.shieldInterval?Math.max(8,s.shieldInterval-3):18}
  ],
  company:[
    {icon:"\u6162",name:"\u6162\u6162\u6765\uff0c\u6211\u4eec\u4e0d\u6025",desc:"\u5168\u573a\u654c\u4eba\u51cf\u901f 12%",apply:s=>s.slow=Math.min(.5,s.slow+.12)},
    {icon:"\u62b1",name:"\u62b1\u4e00\u4e0b\u5c31\u597d",desc:"\u66b4\u6012\u51b2\u523a\u4f24\u5bb3\u964d\u4f4e 40%",apply:s=>s.rageReduction=Math.min(.8,s.rageReduction+.4)},
    {icon:"\u62b1",name:"\u6211\u5728\u5462",desc:"12% \u6982\u7387\u683c\u6321\u4f24\u5bb3",apply:s=>s.block=Math.min(.6,s.block+.12)}
  ]
};
const pick = list => {const available=list.filter(item=>!item.available||item.available(state.stats));return available[Math.floor(Math.random()*available.length)]||list[0];};
const isEnemyVisible = enemy => enemy.x<W-enemy.w*.15&&enemy.x+enemy.w>0;

function reset(){Object.assign(state,{phase:"countdown",lane:1,durability:100,score:0,wave:1,waveTime:0,spawnTime:0,bombTime:0,shotTime:0,level:1,xp:0,xpNeed:5,ultimate:0,invincible:0,shield:0,shieldClock:0,summon:0,worldX:0,shake:0,hurtFlash:0,endingTime:0,nextMemory:0,collected:[],revealed:[],activeMemory:null,memoryResume:"playing",tripleShot:0,powerBuff:0,freezeTime:0,debuffTime:0,finalAssist:0,finalCardDelay:0,finalStoryShown:false,finalVictoryPending:false,stats:baseStats(),bullets:[],enemyShots:[],enemies:[],chests:[],effects:[],eliteSpawned:false,bossSpawned:false,choices:[]});ui.startScreen.classList.add("hidden");ui.endScreen.classList.add("hidden");ui.upgradeScreen.classList.add("hidden");ui.cinematic.classList.add("hidden");ui.memoryScreen.classList.add("hidden");ui.giftScreen.classList.add("hidden");ui.giftMessage.classList.add("hidden");ui.finalRescue.classList.add("hidden");ui.hud.classList.remove("hidden");renderHand();updateHud();countdown();}
async function countdown(){ui.countdown.classList.remove("hidden");for(const value of ["3","2","1","\u6e38\uff01"]){ui.countdown.textContent=value;await new Promise(r=>setTimeout(r,testMode?100:600));}ui.countdown.classList.add("hidden");state.phase="playing";}

function updateHud(){ui.durabilityValue.textContent=`${Math.ceil(state.durability)}/${state.stats.maxDurability}`;ui.scoreValue.textContent=state.score;ui.waveValue.textContent=`${state.wave}/${state.totalWaves}`;ui.levelValue.textContent=state.level;ui.xpValue.textContent=`${state.xp}/${state.xpNeed}`;ui.ultimateBadge.textContent=`\u540c\u5fc3 ${state.collected.length}`;ui.ultimateBadge.classList.toggle("ready",state.collected.length>0);const filled=Math.ceil(5*state.durability/state.stats.maxDurability);ui.heartMeter.replaceChildren(...Array.from({length:5},(_,i)=>{const img=document.createElement("img");img.src=paths.heart[0];img.alt="";if(i>=filled)img.className="empty";return img;}));}
function showToast(text,time=1800){clearTimeout(showToast.timer);ui.toast.textContent=text;ui.toast.classList.remove("hidden");showToast.timer=setTimeout(()=>ui.toast.classList.add("hidden"),time);}
function showMemory(index,finalStory=false){if(state.phase==="memory")return;if(finalStory)state.finalStoryShown=true;state.memoryResume=state.phase==="choice"?"choice":"playing";state.phase="memory";state.activeMemory={index,finalStory};const card=finalStory?finalMemory:memoryCards[index];ui.memoryDate.textContent=card.date;ui.memoryTitle.textContent=card.title;ui.memoryText.textContent=card.text;ui.memoryBackTitle.textContent=finalStory?"\u8fd9\u4e00\u6b21\uff0c\u6211\u4eec\u4e00\u8d77\u628a\u5b83\u53d8\u6210\u771f\u7684":`${card.skill}\uff1a${card.hint}`;const sources=finalStory?paths.finalMemories:[paths.memories[index]];ui.memoryImages.classList.toggle("final-grid",finalStory);ui.memoryImages.replaceChildren(...sources.map(src=>{const img=document.createElement("img");img.src=src;img.alt="";return img;}));ui.memoryCard.classList.remove("flipped");ui.memoryScreen.classList.remove("hidden");sfx("popup");}
function renderHand(){ui.cardHand.replaceChildren(...state.collected.map((index,position)=>{const card=memoryCards[index],button=document.createElement("button");button.type="button";button.className="hand-card";button.style.transform=`rotate(${(position-(state.collected.length-1)/2)*4}deg)`;button.title=`${card.skill}\uff1a${card.hint}`;const img=document.createElement("img");img.src=paths.memories[index];img.alt="";const label=document.createElement("span");label.textContent=card.skill;button.append(img,label);button.addEventListener("click",()=>useMemoryCard(index));return button;}));updateHud();}
function useMemoryCard(index){if(state.phase!=="playing")return;const position=state.collected.indexOf(index);if(position<0)return;state.collected.splice(position,1);state.effects.push({kind:"blast",x:165,y:LANES[state.lane],time:.75,max:.75,radius:175,gold:true});state.summon=Math.max(state.summon,1.15);state.shake=Math.max(state.shake,12);sfx("chest");if(index===0){state.durability=state.stats.maxDurability;state.shield=Math.max(2,state.shield);}if(index===1){state.enemyShots=[];for(const e of state.enemies){if(e.boss)e.hp-=e.maxHp*.25;else e.dead=true;}state.effects.push({kind:"blast",x:W*.55,y:H*.48,time:.9,max:.9,radius:480,gold:true});state.shake=20;}if(index===2){state.tripleShot=Math.max(state.tripleShot,10);state.powerBuff=Math.max(state.powerBuff,10);}if(index===3){state.powerBuff=Math.max(state.powerBuff,12);}if(index===4){state.durability=state.stats.maxDurability;state.invincible=Math.max(state.invincible,6);state.freezeTime=Math.max(state.freezeTime,4);}if(index===5){state.enemyShots=[];state.freezeTime=Math.max(state.freezeTime,10);state.tripleShot=Math.max(state.tripleShot,10);state.powerBuff=Math.max(state.powerBuff,10);}renderHand();showToast(`${memoryCards[index].skill}\uff01`,2400);}
function openChoices(gold=false){state.phase="choice";state.choices=gold?[{icon:"\u8d34",name:"\u91d1\u8272\u00b7\u8d34\u8d34",desc:"\u50a8\u5b58 1 \u6b21\u707f\u707f\u9c7c\u71a0\u71a0\u6e05\u5c4f",apply:()=>state.ultimate++}]:[pick(pools.study),pick(pools.food),pick(pools.company)];ui.choiceEyebrow.textContent=gold?"GOLDEN CHEST":"LOVE & COURAGE";ui.choiceTitle.textContent=gold?"\u6253\u5f00\u91d1\u8272\u5b9d\u7bb1":"\u6536\u4e0b\u4e00\u4efd\u7231\u4e0e\u52c7\u6c14";document.querySelectorAll("[data-choice]").forEach((button,i)=>{const choice=state.choices[i];button.classList.toggle("hidden",!choice);if(choice){button.querySelector(".choice-icon").textContent=choice.icon;button.querySelector("strong").textContent=choice.name;button.querySelector("small").textContent=choice.desc;}});ui.upgradeScreen.classList.remove("hidden");sfx(gold?"chest":"popup");}
function choose(i){const choice=state.choices[i];if(!choice)return;choice.apply(state.stats);ui.upgradeScreen.classList.add("hidden");showToast(choice.name);if(state.xp>=state.xpNeed){state.xp-=state.xpNeed;state.level++;state.xpNeed=5+state.level*2;openChoices(false);}else state.phase="playing";updateHud();}

function difficultyCurve(wave=state.wave){const progress=Math.max(0,Math.min(1,(wave-1)/19));return Math.pow(progress,1.15);}
function spawnEnemy(elite=false){const roll=Math.random();let type="anxiety";if(state.wave===2)type=roll<.7?"anxiety":"weight";if(state.wave>=3)type=roll<.44?"anxiety":roll<.72?"weight":"anger";const base={anxiety:{hp:4,speed:68,w:78,h:100,damage:4,xp:1,frames:paths.anxiety},weight:{hp:14,speed:38,w:105,h:120,damage:8,xp:2,frames:paths.weight},anger:{hp:8,speed:55,w:84,h:105,damage:6,xp:2,frames:paths.anger}}[type];const scale=elite?1.65:1;const curve=difficultyCurve();const late=state.wave>=16?1.3:1;const eliteScale=elite?(state.wave<=6?3.35:4.9):1;const hpScale=(1+curve*2.55)*late*eliteScale;const speedScale=1+curve*.55;const armor=Math.round((type==="weight"?3:0)*(1+curve*1.55));const memoryIndex=elite?[3,6,9,12,15,18].indexOf(state.wave):-1;state.enemies.push({...base,type,lane:Math.floor(Math.random()*3),x:W+80,hp:base.hp*hpScale,maxHp:base.hp*hpScale,speed:base.speed*speedScale,w:base.w*scale,h:base.h*scale,damage:base.damage*(1+curve*1.08)*(elite?1.85:1),xp:base.xp*(elite?5:1),elite,memoryIndex,charge:Math.max(1.05,3.2-curve*1.5)+Math.random(),skill:Math.max(1.15,4.4-curve*2.3)+Math.random(),armor,maxArmor:armor,hit:0});}
function spawnBoss(type){const octopus=type==="octopus";const hp=octopus?300:2200;state.enemies.push({type,lane:1,x:W-330,hp,maxHp:hp,w:octopus?255:340,h:octopus?260:255,speed:octopus?24:38,damage:octopus?35:58,xp:15,frames:octopus?paths.octopus:paths.shark,boss:true,elite:true,charge:2.2,skill:octopus?1.3:.7,hit:0});state.shake=10;showToast(octopus?"\u7ae0\u9c7c\u5fc3\u9b54\u51fa\u73b0\uff01":"\u6700\u540e\u7684\u5fc3\u9b54\u6765\u4e86\uff0c\u6491\u4f4f，\u7b49\u6211\u4eec\u7684\u7ec8\u7ae0\u56de\u5fc6！",3000);}
function spawnBomb(){const curve=difficultyCurve(),hp=12+curve*18;state.enemies.push({type:"bomb",lane:Math.floor(Math.random()*3),x:W+60,hp,maxHp:hp,w:74,h:74,speed:75+curve*55,damage:18+curve*22,xp:3,frames:paths.bomb,bomb:true,float:Math.random()*6,rushClock:1.6+Math.random()*2.2,rushTime:0,hit:0});}
function fire(){const s=state.stats,count=s.bulletCount,lanes=state.tripleShot>0?[0,1,2]:[state.lane],power=state.powerBuff>0?1.7:1;for(const lane of lanes)for(let i=0;i<count;i++){state.bullets.push({x:220,y:LANES[lane]+(i-(count-1)/2)*22,w:38,h:38,speed:560*s.bulletSpeed,damage:s.damage*power,pierce:s.penetrate,explosive:s.explosion,explosionRadius:s.explosionRadius,explosionDamage:s.explosionDamage,dead:false});}}
function hitDefense(enemy){const y=LANES[Math.round(enemy.lane)];damage(enemy.damage*(enemy.type==="anger"?1-state.stats.rageReduction:1),"defense",y);if(enemy.bomb)explodeBomb(enemy,false);else addDeathEffect(enemy);enemy.dead=true;}
function damage(amount,target="player",y=LANES[state.lane]){if((state.phase==="finalRescue"||(state.phase==="memory"&&state.activeMemory?.finalStory))&&state.wave===20)return;if(target==="player"&&(state.invincible>0||Math.random()<state.stats.block))return;if(target==="player"&&state.shield>0){state.shield--;state.effects.push({kind:"blast",x:165,y:LANES[state.lane],time:.45,max:.45,radius:125,gold:true});state.shake=Math.max(state.shake,6);sfx("chest");showToast("\u88ab\u7231\u5b88\u62a4，\u62a4\u76fe\u6321\u4f4f\u4e86\u4f24\u5bb3");return;}const dealt=amount*(1-state.stats.damageReduction),finalStand=state.wave===20&&state.enemies.some(e=>e.type==="shark"&&!e.dead)&&!state.finalStoryShown;state.durability=Math.max(finalStand?1:0,state.durability-dealt);sfx("hurt");if(target==="player"){state.invincible=Math.max(state.invincible,.35);state.effects.push({kind:"playerHit",x:165,y,time:.48,max:.48});state.shake=Math.max(state.shake,9+Math.min(12,dealt*.5));state.hurtFlash=Math.max(state.hurtFlash,.4);}else{state.effects.push({kind:"defenseHit",x:62,y,time:.62,max:.62});state.shake=Math.max(state.shake,14+Math.min(14,dealt*.55));state.hurtFlash=Math.max(state.hurtFlash,.24);}if(finalStand&&state.durability<=1)triggerFinalRescue();else if(state.durability<=0)finish(false);updateHud();}
function addDeathEffect(enemy){state.effects.push({kind:"death",x:enemy.x,y:LANES[Math.round(enemy.lane)],w:enemy.w,h:enemy.h,frames:enemy.frames,time:.5,max:.5});state.shake=Math.max(state.shake,enemy.elite?12:4);}
function explodeBomb(enemy,helpful){sfx("explosion");state.effects.push({kind:"blast",x:enemy.x,y:LANES[Math.round(enemy.lane)],time:.78,max:.78,radius:helpful?175:115});state.shake=Math.max(state.shake,helpful?13:18);if(helpful)for(const other of state.enemies){const sameLane=Math.abs(other.lane-enemy.lane)<.75;if(other!==enemy&&!other.dead&&sameLane&&Math.abs(other.x-enemy.x)<210){other.hp-=Math.min(80,Math.max(30,other.maxHp*.45));}}}
function kill(enemy){enemy.dead=true;if(enemy.bomb)explodeBomb(enemy,true);else addDeathEffect(enemy);state.score++;state.xp+=enemy.xp;const beforeHeal=state.durability;state.durability=Math.min(state.stats.maxDurability,state.durability+state.stats.healOnKill);const healed=state.durability-beforeHeal;if(healed>0)state.effects.push({kind:"heal",x:165,y:LANES[state.lane],amount:Math.round(healed*10)/10,time:.85,max:.85});if(enemy.elite&&!enemy.boss&&enemy.memoryIndex>=0&&!state.revealed.includes(enemy.memoryIndex)){state.revealed.push(enemy.memoryIndex);state.chests.push({x:enemy.x,y:LANES[Math.round(enemy.lane)],w:92,h:82,speed:180,cardIndex:enemy.memoryIndex});updateHud();return;}if(enemy.boss){if(enemy.type==="shark"&&state.finalStoryShown){state.phase="bossExplosion";state.bossDeathTimer=2.4;state.enemyShots=[];const y=LANES[Math.round(enemy.lane)],cx=enemy.x+enemy.w*.5;for(let i=0;i<9;i++)state.effects.push({kind:"blast",x:cx+(i%3-1)*75,y:y+(Math.floor(i/3)-1)*62,time:.65+i*.13,max:.65+i*.13,radius:110+i%3*28,gold:true});state.shake=30;sfx("explosion");}updateHud();return;}if(state.xp>=state.xpNeed){state.xp-=state.xpNeed;state.level++;state.xpNeed=5+state.level*2;openChoices(false);}updateHud();}
function ultimate(){if(state.phase!=="playing"||state.ultimate<1)return;state.ultimate--;state.summon=5;state.invincible=5;ui.cinematic.classList.remove("hidden");setTimeout(()=>{if(state.summon>0){state.enemyShots=[];for(const e of state.enemies){if(e.elite)e.hp-=Math.max(45,e.maxHp*.6);else e.dead=true;}state.effects.push({kind:"blast",x:W*.48,y:H*.48,time:.8,max:.8,radius:430,gold:true});state.shake=24;}},700);setTimeout(()=>ui.cinematic.classList.add("hidden"),1900);updateHud();showToast("\u707f\u707f\u9c7c\u71a0\u71a0\u6765\u4e86\uff01",2500);}

function beginEnding(){state.phase="ending";state.endingTime=0;state.bullets=[];state.enemyShots=[];state.enemies=[];state.chests=[];state.effects=[];state.shake=8;clearTimeout(showToast.timer);ui.toast.classList.add("hidden");ui.cinematic.classList.add("hidden");ui.upgradeScreen.classList.add("hidden");ui.hud.classList.add("hidden");}
function showGift(){state.phase="gift";state.summon=0;ui.giftChestButton.classList.remove("hidden");ui.giftMessage.classList.add("hidden");ui.giftScreen.classList.remove("hidden");}
function triggerFinalRescue(){if(state.finalStoryShown||state.phase==="finalRescue")return;state.phase="finalRescue";state.durability=1;state.invincible=30;state.enemyShots=[];state.shake=18;clearTimeout(showToast.timer);ui.toast.classList.add("hidden");ui.finalRescue.classList.remove("hidden");sfx("win");updateHud();}

function update(dt){
  if(state.phase==="ending"){state.endingTime+=dt;state.worldX=(state.worldX-128*dt)%W;state.shake=Math.max(0,state.shake-25*dt);if(state.endingTime>=(testMode?4.2:9.5))showGift();return;}
  if(state.phase==="bossExplosion"){state.bossDeathTimer=Math.max(0,state.bossDeathTimer-dt);state.shake=Math.max(0,state.shake-16*dt);for(const effect of state.effects)effect.time-=dt;state.effects=state.effects.filter(effect=>effect.time>0);if(state.bossDeathTimer<=0)beginEnding();return;}
  if(state.phase!=="playing")return;
  const s=state.stats;
  state.invincible=Math.max(0,state.invincible-dt);state.summon=Math.max(0,state.summon-dt);state.tripleShot=Math.max(0,state.tripleShot-dt);state.powerBuff=Math.max(0,state.powerBuff-dt);state.freezeTime=Math.max(0,state.freezeTime-dt);state.debuffTime=Math.max(0,state.debuffTime-dt);state.finalAssist=Math.max(0,state.finalAssist-dt);state.finalCardDelay=Math.max(0,state.finalCardDelay-dt);state.shake=Math.max(0,state.shake-28*dt);state.hurtFlash=Math.max(0,state.hurtFlash-dt);state.worldX=(state.worldX-112*dt)%W;state.spawnTime+=dt;state.bombTime+=dt;state.shotTime+=dt;state.shieldClock+=dt;for(const effect of state.effects)effect.time-=dt;state.effects=state.effects.filter(e=>e.time>0);
  const bossAlive=state.enemies.some(e=>e.boss&&!e.dead);
  if(!bossAlive)state.waveTime+=dt;
  if(state.shotTime>=.48/(s.fireRate*(state.powerBuff>0?1.8:1)*(state.debuffTime>0?.55:1))){state.shotTime=0;fire();}
  if(s.shieldInterval&&state.shieldClock>=s.shieldInterval){state.shieldClock=0;state.shield=Math.min(2,state.shield+1);showToast("\u751f\u6210\u4e00\u5c42\u4e34\u65f6\u62a4\u76fe");}
  if((state.wave===10||state.wave===20)&&!state.bossSpawned){state.bossSpawned=true;spawnBoss(state.wave===10?"octopus":"shark");}
  const currentBoss=state.enemies.some(e=>e.boss&&!e.dead);
  const wavesActive=(state.wave<state.totalWaves||state.waveTime<state.waveLength)&&!currentBoss;
  const curve=difficultyCurve(),spawnDelay=3.15-curve*2.5,enemyCap=3+Math.floor(curve*16);if(wavesActive&&state.enemies.length<enemyCap&&state.spawnTime>=spawnDelay){state.spawnTime=0;spawnEnemy(false);}
  if(wavesActive&&state.wave>=6&&state.bombTime>=14.5-curve*9){state.bombTime=0;spawnBomb();}
  if([3,6,9,12,15,18].includes(state.wave)&&!state.eliteSpawned){state.eliteSpawned=true;spawnEnemy(true);showToast("\u8fd9\u4e00\u6ce2\u85cf\u7740\u4e00\u6bb5\u5171\u540c\u56de\u5fc6\u2026\u2026",2600);}
  if(state.waveTime>=state.waveLength&&state.wave<state.totalWaves&&!currentBoss){state.wave++;state.waveTime=0;state.eliteSpawned=false;state.bossSpawned=false;showToast(`\u53c8\u5411\u6211\u4eec\u7684\u672a\u6765\u6e38\u8fd1\u4e00\u7a0b \u00b7 ${state.wave}`);}
  for(const b of state.bullets)b.x+=b.speed*dt;
  for(const shot of state.enemyShots){shot.x-=shot.speed*dt;const laneReach=state.debuffTime>0?175:70,sameLane=Math.abs(shot.y-LANES[state.lane])<laneReach;if(shot.x<215&&shot.x>65&&sameLane&&!shot.dead){if(shot.debuff){state.debuffTime=Math.max(state.debuffTime,5);state.effects.push({kind:"blast",x:165,y:LANES[state.lane],time:.55,max:.55,radius:95});showToast("\u8d2a\u5403\u5370\u8bb0：5 \u79d2\u5185\u9526\u9ca4\u53d8\u80d6，\u653b\u901f\u964d\u4f4e！",2600);}damage(shot.damage,"player",shot.y);shot.dead=true;}else if(shot.x<=40&&!shot.dead){shot.dead=true;}}
  for(const e of state.enemies){
    let speed=e.speed*(1-s.slow)*(state.freezeTime>0?.12:1);e.skill=(e.skill||2)-dt;e.hit=Math.max(0,e.hit-dt);
    if((e.type==="anger"&&state.wave>=4)||e.type==="shark"){e.charge-=dt;if(e.charge<=0){speed*=e.type==="shark"?4:3;e.lane=e.type==="shark"?state.lane:e.lane;e.charge=e.type==="shark"?3:Math.max(1.6,3.1-curve);}}
    if(e.type==="anxiety"&&state.wave>=5&&e.skill<=0&&e.x<W-100){state.enemyShots.push({x:e.x,y:LANES[Math.round(e.lane)],w:34,h:34,speed:225+curve*100,damage:4+curve*5,tint:"blue"});e.skill=Math.max(1.25,4.2-curve*2.3);}
    if(e.type==="weight"&&state.wave>=3&&e.skill<=0){e.armor=Math.min(e.maxArmor,e.armor+4);if(state.wave>=7)state.enemyShots.push({x:e.x,y:LANES[Math.round(e.lane)],w:42,h:42,speed:195+curve*55,damage:3+curve*3,tint:"orange",debuff:true});e.skill=Math.max(2.6,5.2-curve*1.8);}
    if(e.type==="octopus"&&e.skill<=0){for(let lane=0;lane<3;lane++)state.enemyShots.push({x:e.x,y:LANES[lane],w:42,h:42,speed:300,damage:9,tint:"purple"});e.skill=1.8;}
    if(e.type==="shark"&&e.skill<=0){for(let lane=0;lane<3;lane++)state.enemyShots.push({x:e.x,y:LANES[lane],w:46,h:46,speed:390,damage:12,tint:"purple"});e.skill=.72;}
    e.x-=speed*dt;
    if(e.bomb){e.float+=dt*2.4;e.rushClock-=dt;e.rushTime=Math.max(0,e.rushTime-dt);if(e.rushClock<=0&&e.x<W-80){e.rushTime=.9;e.rushClock=3.5+Math.random()*2;state.effects.push({kind:"blast",x:e.x,y:LANES[Math.round(e.lane)],time:.28,max:.28,radius:62});showToast("\u5c0f\u5fc3，\u70b8\u5f39\u9c7c\u8981\u7a81\u8fdb\u4e86！",1000);}if(e.rushTime>0){e.x-=speed*2.15*dt;e.lane+=(state.lane-e.lane)*dt*2.4;}else e.lane=Math.max(0,Math.min(2,e.lane+Math.sin(e.float)*dt*.55));const py=LANES[state.lane],ey=LANES[Math.round(e.lane)];if(Math.abs(e.x-155)<55&&Math.abs(ey-py)<70){damage(e.damage,"player",ey);explodeBomb(e,false);e.dead=true;}}
    if(e.x<65&&!e.dead)hitDefense(e);
  }
  for(const b of state.bullets){for(const e of state.enemies){if(b.dead||e.dead||!isEnemyVisible(e))continue;const ey=LANES[Math.round(e.lane)];if(b.x+b.w>e.x&&b.x<e.x+e.w&&Math.abs(b.y-ey)<e.h*.42){const crit=Math.random()<s.crit;let dealt=b.damage*(crit?s.critDamage:1);if(e.armor>0){const blocked=Math.min(e.armor,dealt);e.armor-=blocked;dealt-=blocked;}e.hp-=dealt;e.hit=.1;if(b.explosive){const blastDamage=(b.damage+3)*b.explosionDamage,blastRadius=b.explosionRadius;sfx("explosion");state.effects.push({kind:"blast",x:e.x+e.w*.35,y:ey,time:.58,max:.58,radius:blastRadius});state.shake=Math.max(state.shake,7);for(const other of state.enemies){const dx=(other.x+other.w*.5)-(e.x+e.w*.5),dy=(LANES[Math.round(other.lane)]-ey)*.72;if(other!==e&&!other.dead&&isEnemyVisible(other)&&Math.hypot(dx,dy)<blastRadius){other.hp-=blastDamage;other.hit=.18;}}}if(e.hp<=0)kill(e);if(b.pierce>0)b.pierce--;else b.dead=true;}}}
  const finalBoss=state.enemies.find(e=>e.type==="shark"&&!e.dead);if(finalBoss&&!state.finalStoryShown){finalBoss.hp=Math.max(finalBoss.hp,finalBoss.maxHp*.92);const progress=Math.max(0,Math.min(1,(W-330-finalBoss.x)/(W-330-W*.52)));state.durability=Math.min(state.durability,Math.max(1,state.stats.maxDurability-(state.stats.maxDurability-1)*progress));if(finalBoss.x<=W*.52||state.durability<=1)triggerFinalRescue();}
  if(state.finalAssist>0){const boss=state.enemies.find(e=>e.boss&&!e.dead);if(boss){boss.hp-=220*dt;boss.hit=.12;state.shake=Math.max(state.shake,5);}}
  for(const chest of state.chests){chest.x-=chest.speed*dt;if(chest.x<=250&&!chest.dead){chest.dead=true;showMemory(chest.cardIndex,false);}}
  state.bullets=state.bullets.filter(b=>!b.dead&&b.x<W+80);state.enemyShots=state.enemyShots.filter(b=>!b.dead&&b.x>40);for(const e of state.enemies)if(e.hp<=0&&!e.dead)kill(e);state.enemies=state.enemies.filter(e=>!e.dead);state.chests=state.chests.filter(c=>!c.dead);if(state.phase==="bossExplosion")return;if(state.finalVictoryPending){beginEnding();return;}
  if(state.wave===state.totalWaves&&state.waveTime>=state.waveLength&&state.enemies.length===0&&state.chests.length===0)beginEnding();updateHud();if(testMode)testStatus.textContent=`${state.phase} | L ${state.lane+1} | HP ${Math.ceil(state.durability)} | E ${state.enemies.length} | S ${state.enemyShots.length}`;
}

function imageFit(img,x,y,w,h,alpha=1){ctx.save();ctx.globalAlpha=alpha;const k=Math.min(w/img.width,h/img.height),dw=img.width*k,dh=img.height*k;ctx.drawImage(img,x+(w-dw)/2,y-dh/2,dw,dh);ctx.restore();}
function anim(frames,fps=6){return images[frames[Math.floor(performance.now()/(1000/fps))%frames.length]];}
function drawWaveStrip(y,alpha=.35,speed=1){const img=images[paths.barrier];const width=610,height=72;let x=(state.worldX*speed)%width-width;const bob=Math.sin(performance.now()/420+speed*3)*5;ctx.save();ctx.globalAlpha=alpha;while(x<W+width){ctx.drawImage(img,x,y+bob,width,height);x+=width-8;}ctx.restore();}
function drawEffect(effect){const p=1-effect.time/effect.max;if(effect.kind==="playerHit"){ctx.save();ctx.globalAlpha=1-p;ctx.strokeStyle="#fff4c9";ctx.lineWidth=5*(1-p)+2;ctx.beginPath();ctx.arc(effect.x,effect.y,22+p*64,0,Math.PI*2);ctx.stroke();for(let i=0;i<10;i++){const a=i*Math.PI/5,dist=24+p*72;ctx.fillStyle=i%2?"#ffffff":"#72d7e8";ctx.beginPath();ctx.arc(effect.x+Math.cos(a)*dist,effect.y+Math.sin(a)*dist,4+i%3,0,Math.PI*2);ctx.fill();}ctx.restore();return;}if(effect.kind==="defenseHit"){ctx.save();ctx.globalAlpha=1-p;ctx.strokeStyle="#ffcf65";ctx.lineWidth=8*(1-p)+3;for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(effect.x+i*16,effect.y,18+p*(45+i*12),55+p*(70+i*10),0,0,Math.PI*2);ctx.stroke();}ctx.fillStyle=`rgba(255,89,43,${(1-p)*.32})`;ctx.fillRect(50,effect.y-95,25,190);ctx.restore();return;}if(effect.kind==="death"){ctx.save();ctx.globalAlpha=1-p;ctx.translate(effect.x+effect.w/2,effect.y);ctx.scale(1+p*.35,1-p*.6);imageFit(anim(effect.frames,5),-effect.w/2,0,effect.w,effect.h);ctx.restore();for(let i=0;i<6;i++){ctx.fillStyle=`rgba(125,211,226,${1-p})`;ctx.beginPath();ctx.arc(effect.x+effect.w/2+Math.cos(i)*p*70,effect.y+Math.sin(i*2.1)*p*55,5+p*5,0,Math.PI*2);ctx.fill();}return;}ctx.save();ctx.globalAlpha=1-p;const radius=Math.max(1,effect.radius*p);const glow=ctx.createRadialGradient(effect.x,effect.y,0,effect.x,effect.y,radius);glow.addColorStop(0,effect.gold?"rgba(255,255,210,.95)":"rgba(255,250,195,.95)");glow.addColorStop(.3,effect.gold?"rgba(255,199,47,.65)":"rgba(255,116,39,.72)");glow.addColorStop(1,"rgba(180,35,20,0)");ctx.fillStyle=glow;ctx.beginPath();ctx.arc(effect.x,effect.y,radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle=effect.gold?"#ffd85c":"#ff8f4b";ctx.lineWidth=18*(1-p)+3;ctx.beginPath();ctx.arc(effect.x,effect.y,radius,0,Math.PI*2);ctx.stroke();for(let i=0;i<14;i++){const angle=i*Math.PI*2/14+.3,dist=radius*(.55+(i%3)*.15);ctx.fillStyle=i%2?"#ffd05a":"#ff6a2e";ctx.beginPath();ctx.arc(effect.x+Math.cos(angle)*dist,effect.y+Math.sin(angle)*dist,3+i%4,0,Math.PI*2);ctx.fill();}ctx.restore();}
function drawShield(now){if(state.shield<=0)return;const x=165,y=LANES[state.lane],pulse=1+Math.sin(now/180)*.035,angle=now/720;ctx.save();ctx.strokeStyle="rgba(255,219,91,.88)";ctx.fillStyle="rgba(255,218,77,.06)";ctx.shadowColor="#ffd34d";ctx.shadowBlur=18;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(x,y,108*pulse,73*pulse,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=8;for(let i=0;i<9;i++){const a=angle+i*Math.PI*2/9;ctx.fillStyle=i%2?"#fff2a6":"#ffc83d";ctx.beginPath();ctx.arc(x+Math.cos(a)*105,y+Math.sin(a)*70,3+(i%3),0,Math.PI*2);ctx.fill();}ctx.restore();const guardX=x+Math.cos(-angle*1.4)*100,guardY=y+Math.sin(-angle*1.4)*62;imageFit(anim(paths.summon,6),guardX-29,guardY,58,64,.92);}
function drawHeal(effect){const p=1-effect.time/effect.max;ctx.save();ctx.globalAlpha=1-p;ctx.strokeStyle="#e7bd4f";ctx.fillStyle="rgba(91,190,112,.16)";ctx.shadowColor="#ffe178";ctx.shadowBlur=18;ctx.lineWidth=5*(1-p)+2;ctx.beginPath();ctx.arc(effect.x,effect.y,38+p*58,0,Math.PI*2);ctx.fill();ctx.stroke();for(let i=0;i<7;i++){const a=i*Math.PI*2/7+p*2,dist=35+p*65;ctx.fillStyle=i%2?"#fff0a1":"#69cf83";ctx.beginPath();ctx.arc(effect.x+Math.cos(a)*dist,effect.y+Math.sin(a)*dist,4,0,Math.PI*2);ctx.fill();}ctx.shadowBlur=8;ctx.textAlign="center";ctx.font="bold 28px STXinwei, KaiTi";ctx.strokeStyle="#fff2b5";ctx.lineWidth=5;ctx.strokeText(`+${effect.amount}`,effect.x,effect.y-55-p*36);ctx.fillStyle="#27854b";ctx.fillText(`+${effect.amount}`,effect.x,effect.y-55-p*36);ctx.restore();}
function drawDebuff(now){if(state.debuffTime<=0)return;const x=165,y=LANES[state.lane],angle=now/330;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.strokeStyle="rgba(160,39,31,.82)";ctx.lineWidth=5;ctx.setLineDash([12,8]);ctx.beginPath();ctx.ellipse(0,0,142,126,0,0,Math.PI*2);ctx.stroke();ctx.rotate(-angle*2);ctx.strokeStyle="rgba(225,171,54,.72)";ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,0,122,108,0,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.save();ctx.textAlign="center";ctx.font="bold 19px STXinwei, KaiTi";ctx.fillStyle="#8f2d24";ctx.strokeStyle="#ffe19a";ctx.lineWidth=5;ctx.strokeText("\u8d2a\u5403\u5370\u8bb0 \u00b7 \u653b\u901f\u964d\u4f4e \u00b7 \u53d7\u51fb\u8303\u56f4\u6269\u5927",x,y-148);ctx.fillText("\u8d2a\u5403\u5370\u8bb0 \u00b7 \u653b\u901f\u964d\u4f4e \u00b7 \u53d7\u51fb\u8303\u56f4\u6269\u5927",x,y-148);ctx.restore();}
function drawFinalAssist(now){if(state.finalAssist<=0&&state.phase!=="bossExplosion")return;const y=LANES[state.lane]+82+Math.sin(now/160)*6;ctx.save();ctx.globalAlpha=.18+.1*Math.sin(now/70);ctx.fillStyle="#ffd95a";ctx.beginPath();ctx.arc(175,y,72,0,Math.PI*2);ctx.fill();ctx.restore();imageFit(anim(paths.summon,7),120,y,110,126);const boss=state.enemies.find(e=>e.type==="shark"&&!e.dead);if(boss&&state.finalAssist>0){ctx.save();ctx.strokeStyle="rgba(255,213,74,.8)";ctx.shadowColor="#ffcf3b";ctx.shadowBlur=14;ctx.lineWidth=4;for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(220,y+(i-1)*12);ctx.lineTo(boss.x+20,LANES[Math.round(boss.lane)]+(i-1)*24);ctx.stroke();}ctx.restore();}}
function drawEnemy(enemy,now){const y=LANES[Math.round(enemy.lane)];if(enemy.bomb&&enemy.rushTime>0){ctx.save();ctx.globalAlpha=.22+.16*Math.sin(now/45);ctx.fillStyle="#ff6a2d";for(let i=1;i<=4;i++){ctx.beginPath();ctx.ellipse(enemy.x+enemy.w*.5+i*28,y,enemy.w*(.58-i*.08),enemy.h*(.42-i*.05),0,0,Math.PI*2);ctx.fill();}ctx.strokeStyle="#ffd05a";ctx.lineWidth=5;ctx.beginPath();ctx.arc(enemy.x+enemy.w*.5,y,enemy.w*.72+Math.sin(now/50)*8,0,Math.PI*2);ctx.stroke();ctx.restore();}imageFit(anim(enemy.frames,5),enemy.x,y,enemy.w,enemy.h,enemy.hit?.52:1);const barY=y-enemy.h/2-16;ctx.fillStyle="rgba(35,27,25,.8)";ctx.fillRect(enemy.x,barY,enemy.w,9);ctx.fillStyle=enemy.boss?"#bd69d1":enemy.elite?"#e3b438":"#c83b31";ctx.fillRect(enemy.x,barY,enemy.w*Math.max(0,enemy.hp/enemy.maxHp),9);if(enemy.armor>0){ctx.fillStyle="#65c8db";ctx.fillRect(enemy.x,barY-7,enemy.w*(enemy.armor/enemy.maxArmor),4);}if(enemy.boss){ctx.fillStyle="rgba(255,250,232,.9)";ctx.font="bold 19px STXinwei, KaiTi";ctx.fillText(enemy.type==="octopus"?"\u7ae0\u9c7c\u5fc3\u9b54":"\u6df1\u6d77\u9ca8\u9c7c",enemy.x,barY-12);}}
function draw(now){
  if(!ready){ctx.fillStyle="#eadcbd";ctx.fillRect(0,0,W,H);return;}
  ctx.save();if(state.shake>0)ctx.translate((Math.random()-.5)*state.shake,(Math.random()-.5)*state.shake);
  ctx.drawImage(images[paths.background],0,0,W,H);
  const shimmer=(Math.sin(now/700)+1)/2;ctx.fillStyle=`rgba(111,190,202,${.04+shimmer*.035})`;ctx.fillRect(0,80,W,H-110);
  drawWaveStrip(112,.18,.38);drawWaveStrip(268,.22,.56);
  for(let i=0;i<3;i++){const y=LANES[i];ctx.beginPath();ctx.moveTo(55,y-64);ctx.bezierCurveTo(340,y-88,720,y-38,W,y-67);ctx.lineTo(W,y+63);ctx.bezierCurveTo(820,y+38,430,y+88,55,y+61);ctx.closePath();ctx.fillStyle=i%2?"rgba(52,132,150,.11)":"rgba(37,105,130,.15)";ctx.fill();drawWaveStrip(y+45,.3,.78+i*.13);}
  ctx.fillStyle="rgba(164,48,39,.6)";ctx.fillRect(54,120,8,470);ctx.fillStyle="rgba(255,235,188,.7)";ctx.fillRect(62,120,2,470);
  for(const chest of state.chests)imageFit(images[paths.chest],chest.x,chest.y,chest.w,chest.h);
  for(const b of state.bullets)imageFit(anim(paths.bullet,10),b.x,b.y,b.w,b.h);
  for(const shot of state.enemyShots){ctx.save();ctx.filter=shot.tint==="purple"?"hue-rotate(235deg) saturate(1.7)":shot.tint==="orange"?"hue-rotate(8deg) saturate(2.1) brightness(1.1)":"hue-rotate(145deg) saturate(1.8)";imageFit(anim(paths.bullet,10),shot.x,shot.y,shot.w,shot.h);ctx.restore();}
  for(const e of state.enemies)drawEnemy(e,now);
  for(const effect of state.effects)effect.kind==="heal"?drawHeal(effect):drawEffect(effect);
  if(["countdown","playing","choice","finalRescue","bossExplosion"].includes(state.phase)){const fat=state.debuffTime>0;imageFit(anim(paths.player,6),fat?20:92,LANES[state.lane]+Math.sin(now/190)*4,fat?285:145,fat?270:90,state.invincible>0&&Math.floor(now/90)%2?.45:1);drawShield(now);drawDebuff(now);drawFinalAssist(now);}
  drawWaveStrip(575,.78,1.35);imageFit(images[paths.tallWave],-38,LANES[state.lane]+42,155,155,.72);
  if(state.summon>0){const fall=Math.min(1,(5-state.summon)/.72),y=-380+fall*720;ctx.save();ctx.globalAlpha=.28+.18*Math.sin(now/70);ctx.fillStyle="#ffd34d";ctx.beginPath();ctx.arc(535,y,210+fall*90,0,Math.PI*2);ctx.fill();ctx.restore();imageFit(anim(paths.summon,6),345,y,380,455);ctx.fillStyle="rgba(255,220,83,.13)";ctx.fillRect(0,0,W,H);}
  const wave=images[paths.wave];let wx=state.worldX%W;ctx.globalAlpha=.92;ctx.drawImage(wave,wx,H-72,W,82);ctx.drawImage(wave,wx+W,H-72,W,82);ctx.globalAlpha=1;
  if(state.hurtFlash>0){ctx.fillStyle=`rgba(210,35,28,${state.hurtFlash*.65})`;ctx.fillRect(-30,-30,W+60,H+60);}
  if(state.wave===20&&state.bossSpawned&&["playing","finalRescue","memory","bossExplosion"].includes(state.phase)){const darkness=(1-state.durability/state.stats.maxDurability)*(state.finalAssist>0?.22:.62);ctx.fillStyle=`rgba(5,7,10,${Math.max(0,darkness)})`;ctx.fillRect(0,0,W,H);}
  ctx.restore();
  if(state.phase==="ending")drawEnding(now);
}
function easeOut(t){return 1-Math.pow(1-Math.max(0,Math.min(1,t)),3);}
function drawEnding(now){
  const duration=testMode?4.2:9.5,t=state.endingTime,scale=duration/6.5;
  const gateEnter=easeOut(t/(1.55*scale));
  const gateX=W+180-gateEnter*470;
  ctx.save();
  if(t>1.1*scale){const swim=easeOut((t-1.1*scale)/(3.9*scale));const fishX=120+swim*1120;const bob=Math.sin(now/130)*5;imageFit(anim(paths.player,7),fishX,335+bob,175,108);imageFit(anim(paths.summon,7),fishX-38,455-bob,150,185);}
  imageFit(images[paths.gate],gateX,345,245,390);
  if(t>3.5*scale){const fade=Math.min(1,(t-3.5*scale)/(1.1*scale)),glow=.82+.18*Math.sin(now/260);ctx.fillStyle=`rgba(255,242,190,${fade*.68})`;ctx.fillRect(0,0,W,H);ctx.globalAlpha=fade;ctx.textAlign="center";ctx.font="bold 76px STXingkai, KaiTi";ctx.lineWidth=9;ctx.strokeStyle="rgba(80,42,20,.72)";ctx.shadowColor=`rgba(255,196,45,${glow})`;ctx.shadowBlur=30;ctx.strokeText("\u6211\u4eec\u7ec8\u5c06\u643a\u624b\u4e0a\u5cb8",W/2,270);ctx.fillStyle="#e7b94e";ctx.fillText("\u6211\u4eec\u7ec8\u5c06\u643a\u624b\u4e0a\u5cb8",W/2,270);ctx.shadowBlur=8;ctx.font="bold 36px STXingkai, KaiTi";ctx.lineWidth=5;ctx.strokeStyle="#f5d77f";ctx.strokeText("\u5bf9\u7684\u4eba\u4f1a\u7ad9\u5728\u5f7c\u6b64\u7684\u524d\u9014\u91cc",W/2,340);ctx.fillStyle="#932f26";ctx.fillText("\u5bf9\u7684\u4eba\u4f1a\u7ad9\u5728\u5f7c\u6b64\u7684\u524d\u9014\u91cc",W/2,340);ctx.shadowBlur=0;ctx.globalAlpha=1;}
  ctx.restore();
}
function finish(won){state.phase=won?"won":"lost";clearTimeout(showToast.timer);ui.toast.classList.add("hidden");ui.hud.classList.add("hidden");ui.endScreen.classList.remove("hidden");ui.endEyebrow.textContent=won?"200 DAYS TOGETHER":"\u6572\u6572\u6728\u5934";ui.endTitle.textContent=won?"\u6211\u4eec\u7ec8\u5c06\u643a\u624b\u4e0a\u5cb8\uff1b":"\u5931\u8bef\u5566\uff0c\u6ca1\u5173\u7cfb";ui.endMessage.textContent=won?"\u5bf9\u7684\u4eba\u4f1a\u7ad9\u5728\u5f7c\u6b64\u7684\u524d\u9014\u91cc\uff1b":"\u8fd9\u53ea\u662f\u4e00\u6b21\u5c0f\u5c0f\u7684\u91cd\u6765\u3002\u6572\u6572\u6728\u5934\uff0c\u6211\u4eec\u518d\u8bd5\u4e00\u6b21\u5427~";ui.finalScore.textContent=state.score;sfx(won?"win":"hurt");if(testMode)testStatus.textContent=state.phase;}

let previous=performance.now();function loop(now){const dt=Math.min(.05,(now-previous)/1000);previous=now;update(dt);draw(now);requestAnimationFrame(loop);}requestAnimationFrame(loop);
function handleKey(code){if(state.phase!=="playing")return;if(code==="ArrowUp"||code==="KeyW")state.lane=Math.max(0,state.lane-1);if(code==="ArrowDown"||code==="KeyS")state.lane=Math.min(2,state.lane+1);if(code==="Space")ultimate();}
window.addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","Space"].includes(e.code))e.preventDefault();if(!e.repeat)handleKey(e.code);});
document.querySelectorAll("[data-key]").forEach(b=>b.addEventListener("pointerdown",e=>{e.preventDefault();handleKey(b.dataset.key);}));
let touchStartY=null;
canvas.addEventListener("pointerdown",event=>{if(event.pointerType!=="mouse")touchStartY=event.clientY;});
canvas.addEventListener("pointerup",event=>{if(touchStartY===null||event.pointerType==="mouse")return;const delta=event.clientY-touchStartY;touchStartY=null;if(Math.abs(delta)>24)handleKey(delta<0?"ArrowUp":"ArrowDown");});
canvas.addEventListener("pointercancel",()=>{touchStartY=null;});
ui.startButton.addEventListener("click",()=>{if(!ready)return;unlockAudio();reset();});ui.restartButton.addEventListener("click",()=>{unlockAudio();reset();});ui.audioToggle.addEventListener("click",toggleAudio);document.querySelectorAll("[data-choice]").forEach(b=>b.addEventListener("click",()=>choose(Number(b.dataset.choice))));
ui.flipMemoryButton.addEventListener("click",()=>{sfx("flip");ui.memoryCard.classList.add("flipped");});
ui.keepMemoryButton.addEventListener("click",()=>{
  const active=state.activeMemory;
  if(!active)return;
  ui.memoryScreen.classList.add("hidden");
  ui.memoryCard.classList.remove("flipped");
  if(active.finalStory){
    state.phase="playing";
    state.finalAssist=14;
    state.summon=5;
    state.invincible=Math.max(state.invincible,18);
    state.tripleShot=Math.max(state.tripleShot,14);
    state.powerBuff=Math.max(state.powerBuff,14);
    state.enemyShots=[];
    state.effects.push({kind:"blast",x:W*.5,y:H*.48,time:1,max:1,radius:500,gold:true});
    state.shake=24;
    sfx("win");
    showToast("\u6700\u540e\u4e00\u7a0b，\u707f\u707f\u4e0e\u71a0\u71a0\u5e76\u80a9\u8d8a\u8fc7！",3000);
  }else{
    const index=active.index;
    if(!state.collected.includes(index))state.collected.push(index);
    state.nextMemory=Math.max(state.nextMemory,index+1);
    state.stats.damage+=.35;
    state.stats.fireRate*=1.05;
    state.stats.maxDurability+=5;
    state.durability=Math.min(state.stats.maxDurability,state.durability+5);
    state.phase="playing";
    renderHand();
    showToast("\u56de\u5fc6\u5df2\u6536\u597d，\u9526\u9ca4\u53c8\u53d8\u5f3a\u4e86\u4e00\u70b9");
  }
  state.activeMemory=null;
  updateHud();
});
ui.giftChestButton.addEventListener("click",()=>{sfx("win");ui.giftChestButton.classList.add("hidden");ui.giftMessage.classList.remove("hidden");});
ui.finalChestButton.addEventListener("click",()=>{ui.finalRescue.classList.add("hidden");state.finalStoryShown=true;sfx("chest");showMemory(6,true);});
document.querySelector('[data-test="rush"]')?.addEventListener("click",()=>{if(!testMode||state.phase!=="playing")return;spawnBomb();const bomb=state.enemies[state.enemies.length-1];bomb.x=760;bomb.lane=state.lane;bomb.hp=bomb.maxHp=80;bomb.rushClock=.05;});
document.querySelector('[data-test="heal"]')?.addEventListener("click",()=>{if(!testMode||state.phase!=="playing")return;state.durability=Math.min(70,state.stats.maxDurability);state.stats.healOnKill=2;spawnEnemy(false);const enemy=state.enemies[state.enemies.length-1];enemy.x=330;enemy.lane=state.lane;enemy.hp=enemy.maxHp=1;updateHud();});
document.querySelectorAll("[data-test]").forEach(b=>b.addEventListener("click",()=>{if(!testMode)return;const a=b.dataset.test;if(a==="level")openChoices(false);if(a==="gold"||a==="card")showMemory(Math.min(state.nextMemory,5),false);if(a==="finalcard")showMemory(6,true);if(a==="bomb"){spawnEnemy(false);spawnEnemy(false);const near=state.enemies.slice(-2);near[0].x=430;near[1].x=500;near[0].lane=near[1].lane=state.lane;spawnBomb();const bomb=state.enemies[state.enemies.length-1];bomb.x=360;bomb.lane=state.lane;bomb.hp=2;bomb.maxHp=2;}if(a==="splash"){state.stats.explosion=1;state.stats.explosionRadius=180;state.stats.explosionDamage=1.8;state.stats.damage=5;state.stats.bulletCount=3;for(let i=0;i<3;i++){spawnEnemy(false);const target=state.enemies[state.enemies.length-1];target.type="anxiety";target.x=365+i*65;target.lane=state.lane;target.hp=target.maxHp=8;}}if(a==="late"){state.enemies=[];state.enemyShots=[];state.wave=16;state.waveTime=0;state.eliteSpawned=false;state.bossSpawned=false;}if(a==="boss"||a==="boss2"){state.enemies=[];state.wave=a==="boss"?10:20;state.waveTime=0;state.bossSpawned=false;}if(a==="damage")damage(20,"player",LANES[state.lane]);if(a==="defense")damage(20,"defense",LANES[state.lane]);if(a==="shield"){state.shield=2;updateHud();}if(a==="debuff")state.debuffTime=5;if(a==="rescue"){state.wave=20;state.bossSpawned=true;state.finalStoryShown=false;if(!state.enemies.some(e=>e.type==="shark"))spawnBoss("shark");triggerFinalRescue();}if(a==="win"){state.wave=state.totalWaves;state.waveTime=state.waveLength;state.eliteSpawned=true;state.bossSpawned=true;state.finalStoryShown=true;state.enemies=[];}}));
